travis:
  secure:
    BINSTAR_TOKEN: WKefZmJ4XBr147thdVJHVgVCAr18YLhjXBXZycr4ger54nSJciJURg0OnCPl8uDvuoIoPgpI1PzSXlBt7cDWnkAQlam1fzisQD+oOxv+xRwO+AKibrPbj4+fEtPNVsbt8I3DyoVoxAY9mTsDjVR5eitjiMvhIQGXeX9PekSlqwuiCVwV2bsQ7Ct0sIP+Z3PrOapDPuHA0D1oC2vn14gklNL2hLpniWbpxTk/r9A+6/v6qRp8Qt/LFoU0gb9Lgoxlx/L+s+9mXIIwV3hJDkpiRLGQ1mlFjTvDDIU9XeDjmOINhUAPjkZZ3uDjGBuUbj264AKAMwUwDXZ/tBmgG3KqYfsez0jz7YY4GqfdgV7Gnllyoo0MBNQB83Tx0oJcArO2irG23JKY8iF8S694rg4KLiAHj7N1S+8Fmmdgi04vZAR0OyTMaUbwaXF4QcajbKbDNne5K8poBax5bhJIJrKMcvZ8pVHKP7hOsvwO0MZtKWHtkB4T+vw6wys8UNfwaM90rZ5I3ai3Jam5fUynJklR3u4hErZzp+4kPzsMQ86WNLUVEsxwEiz61vtEDJOtdFa1I+zmWl8R2ROnV8rRI716TVcRwVnucJXEOoIm6qCvA5FTK9ZIyj54nr/bO1dW3RGMoZCyxyIHzFDvwFb5FRUNnvVmSXN5UXslJyc/vS7+NKc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
